services:
  minio:
    image: "minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1"
    ports:
      - "2590:2590"
      - "2591:2591"
    volumes:
      - "./cache/minio/data1:/data1"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=c9jA9ZvNXLwfs6n6fog6EJ0396Q77TbEm6G1XeDQbFG02GYwBsMh5wcTeJFzquD6sYE5saMGsrLnXernC5VaxjNfUuKqZxGRh9wf
    command: server /data1 --console-address ":2590" --address ":2591" # --console-address web 为界面端口 --address api请求端口

  postgres:
      image: postgres:17-alpine
      restart: always
      ports:
          - "${POSTGRES_PORT:-5432}:5432"
      env_file:
          - ./.env.local
      volumes:
          - postgres_db:/var/lib/postgresql/data

volumes:
  postgres_db:
